# SPDX-License-Identifier: GPL-3.0-only
#
# This file is part of the rubin-os project:
#    https://github.com/ferret-linux/rubin-os
# Copyright (C) 2026 Ferret Linux contributors

name: Build RubinOS

on:
  pull_request:
    branches:
      - stable
  schedule:
    - cron: '05 10 * * *'
  push:
    branches:
      - stable
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/.build.yml
    permissions:
      contents: read
      packages: write

  sbom-grype:
    needs: [build]
    uses: ./.github/workflows/.sbom-grype.yml
    permissions:
      contents: read

  push:
    needs: [sbom-grype]
    if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    uses: ./.github/workflows/.push.yml
    permissions:
      contents: read
      packages: write
      id-token: write

  verify:
    needs: [push]
    if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    uses: ./.github/workflows/.verify.yml
    permissions:
      contents: read
      packages: read

  rollback:
    needs: [verify]
    if: always() && needs.verify.result == 'failure'
    uses: ./.github/workflows/.rollback.yml
    permissions:
      contents: read
      packages: write
    secrets: inherit